image: node:latest

stages:
  - build
  - deploy

before_script:
  - nvm install 14.17.6

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/ 

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
