stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

deploy-job:
  stage: deploy
  environment: production
  before_script:
    - git config --global user.name "GitLab CI/CD"
    - git config --global user.email "gitlab-ci-cd@example.com"
  script:
    - git clone --branch main --depth 1 http://192.168.1.171/root/mrghostlyorb-dev-node/ .
    - echo "Deploying application..."
    - echo "Application successfully deployed."
